main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'


urlpatterns = [
    path('', views.home_view, name="index"),
    path('home/', views.home_inner_view, name="home"),
    path('phones/', views.phone_view, name="phones"),
    path('laptops/', views.laptop_view, name="laptops"),
    path('accessories/', views.accessories_view, name="accessories"),
    path('bid/', views.bid_view, name="bid"),
    path('add-bid/', views.add_bid_view, name="addbid"),
]

phoneApp/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as acctViews

from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', acctViews.login_view, name="login"),
    path('logout/', acctViews.logout_view, name="logout"),


]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

def upload_location(instance, filename):
	file_path = 'goalifix/{image}'.format(image=filename)
	return file_path


# Create your models here.
class Products(models.Model):
	brand        = models.CharField(max_length=100)
	device        = models.CharField(max_length=100)
	price        = models.PositiveIntegerField(blank=True)
	bidPrice     = models.PositiveIntegerField(blank=True, default=0)
	body         = models.TextField()
	date         = models.DateTimeField(auto_now_add=True)
	thumb        = models.ImageField(upload_to=upload_location, blank=True)

	def __str__(self):
		return self.device



# Create your models here.
class Bidder(models.Model):
	name        = models.CharField(max_length=100)
	email        = models.CharField(max_length=100)
	phone        = models.CharField(max_length=100)
	product 	 = models.ForeignKey(Products, default=None, on_delete=models.CASCADE)
	price        = models.PositiveIntegerField(blank=True)
	date         = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name


# Create your models here.
class BidStatus(models.Model):
	active_bid				= models.BooleanField(default=False)
	date         = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.active_bid)

main/forms.py
from django import forms

from .models import Products, Bidder


class CreateProductForm(forms.ModelForm):

	class Meta:
		model = Products
		fields = ['brand', 'device', 'price', 'body', 'thumb']


class CreateBidForm(forms.ModelForm):

	class Meta:
		model = Bidder
		fields = ['name', 'price', 'phone', 'email']
		

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import CreateProductForm, CreateBidForm
from .models import Products, Bidder, BidStatus
from decouple import config
from accounts.models import Account
from django.utils import timezone

import time
from datetime import datetime


# Create your views here.

def home_view(request):

	context = {}

	return render(request, "main/index.html", context)



def home_inner_view(request):

	context = {}
	phoneNumber = config('PhoneNumber')
	context['swap'] = "https://api.whatsapp.com/send/?phone=%2B"+phoneNumber+"&text=Hi,+I+want+to+swap+a+device+"
	context['sell'] = "https://api.whatsapp.com/send/?phone=%2B"+phoneNumber+"&text=Hi,+I+want+to+sell+a+device+"
	context['fix'] = "https://api.whatsapp.com/send/?phone=%2B"+phoneNumber+"&text=Hi,+I+want+to+fix+a+device+"

	return render(request, "main/home.html", context)


def phone_view(request):

	context = {}
	phoneNumber = config('PhoneNumber')
	context['phone'] = "https://api.whatsapp.com/send/?phone=%2B"+phoneNumber+"&text=Hi,+I+want+to+make+enquires+for+a+Phone+"

	return render(request, "main/phones.html", context)


def laptop_view(request):

	context = {}
	phoneNumber = config('PhoneNumber')
	context['phone'] = "https://api.whatsapp.com/send/?phone=%2B"+phoneNumber+"&text=Hi,+I+want+to+make+enquires+for+a+Laptop+"

	return render(request, "main/laptops.html", context)



def accessories_view(request):

	context = {}
	phoneNumber = config('PhoneNumber')
	context['phone'] = "https://api.whatsapp.com/send/?phone=%2B"+phoneNumber+"&text=Hi,+I+want+to+an+Accessory+"

	return render(request, "main/accessories.html", context)

	#Some changes



def bid_view(request):

	context = {}
	status = BidStatus.objects.all().first()
	user = Account.objects.filter(email=request.user)

	if status.active_bid:
		product = Products.objects.all()
	elif not status.active_bid and user:
		product = Products.objects.all()
		context['adminView'] = True
	else:
		product = None


	# now = datetime.datetime.now()
	five_h_ago = timezone.now() - timezone.timedelta(hours=1)
	time1 = five_h_ago
	product = Products.objects.filter(date__gt=five_h_ago).order_by('-id')
		
	context['product'] = product
	

	form = CreateBidForm(request.POST or None, request.FILES or None)
	if request.method == 'POST':   
		if int(request.POST['price']) > int(request.POST['current']):

			item = Products.objects.get(id=request.POST['id'])

			if form.is_valid():
				obj = form.save(commit=False)
				obj.product = item

				item.bidPrice = request.POST['price']
				item.save()
				obj.save()
				form = CreateBidForm()
				context['success'] = "Added successfully"
			else:
				context['error'] = "Error submitting form"
		else:
			context['error'] = "Your price must be higher than current price"
	context['form'] = form

	return render(request, "main/bid.html", context)





@login_required(login_url="/login/")
def add_bid_view(request):

	context = {}
	bidders = Bidder.objects.all()
	context['bidders'] = bidders


	user = Account.objects.get(email=request.user)
	status = BidStatus.objects.all().first()


	form = CreateProductForm(request.POST or None, request.FILES or None)
	if request.method == 'POST':
		if request.POST.get("add-bid"):
			if form.is_valid():
				obj = form.save(commit=False)
				obj.bidPrice = request.POST['price']
				obj.save()
				form = CreateProductForm()
				return redirect("/bid")
			else:
				context['error'] = "Error submitting form"
		
		if request.POST.get("bid-status"):
			status.active_bid = not status.active_bid
			status.save()


		if request.POST.get("delete"):
			bidders.delete()

	context['bidStatus'] = status.active_bid	
	context['product'] = bidders.count()
	context['form'] = form

	return render(request, "main/addbid.html", context)

main/templates/main/bid.html
{% extends 'base.html' %}

{% load static from static %}
{% block content %}

            
    <!-- Custom styles for this template -->
    <link href="{% static 'features.css' %}" rel="stylesheet">
</head>
<body>
    <div class="b-example-divider"></div>
        
       


    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

<style>
.bd-placeholder-img {
font-size: 1.125rem;
text-anchor: middle;
-webkit-user-select: none;
-moz-user-select: none;
user-select: none;
}

@media (min-width: 768px) {
.bd-placeholder-img-lg {
font-size: 3.5rem;
}
}
</style>


</head>
<body>



<main>

<section class="py-5 text-center bg-gradient-primary-to-secondary ">
<div class="row py-lg-5">
<div class="col-lg-6 col-md-8 mx-auto">
<h1 class="fw-light text-light">LETS SEE WHATS UP FOR BIDDING</h1>

<a href="/add-bid" class="btn btn-dark my-2">Place a bid</a>

</div>
</div>
</section>


<!-- Basic features section-->
<div class="b-example-divider"></div>
{% if adminView %}
    <h3 class="mt-3" style="text-align: center;">Bidding is currently turned off. Only you can view this as the admin</h3>
    <p class="mt-3" style="text-align: center;">Go to the <a href="/add-bid"> Admin</a> change to activate Bidding for all users</p>
{% endif %}

{% if success %}
    <h3 class="mt-3" style="color:green; text-align: center;">{{success}}</h3>
{% endif %}
{% if error %}
    <h3 class="mt-3" style="color:red; text-align: center;">{{error}}</h3>
{% endif %}

<section class="bg-light">
 <div class="container px-5">
   
    {% for post in product %}
     <div class="row gx-5 align-items-center justify-content-center justify-content-lg-between  border-bottom">
         <div class="col-12 col-lg-5">
             <div class="px-5 px-sm-0"><img class="img-fluid rounded-circle" src="{{post.thumb.url}}" alt="..." /></div>
            
   
         </div>
         <div class="col-sm-8 col-md-6 p-5">
             <h2 class="display-4 lh-1 mb-4">{{post.brand}}</h2>
             <p class="lead fw-normal text-dark mb-5 mb-lg-0">  
                 name of device: {{post.device}} <br>
                 Current bid: &#8358;{{post.bidPrice}}<br>
                 Device description:
                 <hr>
                 {{post.body}}<br>

                 <div class="mb-3 mt-3">
                    <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <input type="number" class="form-control" name="price" placeholder="Price" required>
                        <input type="text" class="form-control" name="name" placeholder="Full name" required>
                        <input type="number" class="form-control" name="phone" placeholder="Phone number" required>
                        <input type="email" class="form-control" name="email" placeholder="email" required>
                        <input class="form-control" hidden name="current" value="{{post.price}}" readonly required>
                        <input class="form-control" hidden name="id" value="{{post.id}}" readonly required>
                        <button class="btn btn-dark" type="submit" id="button-addon2">Place bid</button>
                    </form>
                   </div>
             </p>
            

     
            
         </div>
     </div>
     {% endfor %}
     {% if not product %}  
        <h2 class="display-6 mb-4">There is no Item for bidding currently</h2>

     {% endif %}



 </div>


<div class="b-example-divider"></div>
{% endblock%}

main/templates/main/index.html
{% extends 'base.html' %}

{% load static from static %}
{% block content %}

   <!-- Mashead header-->
   <header class="masthead">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <!-- Mashead text and app badges-->
                <div class="mb-5 mb-lg-0 text-center text-lg-start">
                    <h1 class="display-1 lh-1 mb-3">Goalifix</h1>
                    <p class="lead fw-normal text-muted mb-5">Welcome to goalifix limited  
                        The world of goalifix limited awaits 
                        We’re so glad you’re here! You are now part of a growing community of professional creating,collaborating and connecting across the globe via goalifix limited whether you’ve joined to create something of your own or just to connect with other professionals we’ve got something for you.
                        Let’s go!</p>
                   
                </div>
            </div>
            <div class="col-lg-6">
                <!-- Masthead device mockup feature-->
                <div class="masthead-device-mockup">
                    <svg class="circle" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                        <defs>
                            <linearGradient id="circleGradient" gradientTransform="rotate(45)">
                                <stop class="gradient-start-color" offset="0%"></stop>
                                <stop class="gradient-end-color" offset="100%"></stop>
                            </linearGradient>
                        </defs>
                        <circle cx="50" cy="50" r="50"></circle></svg
                    ><svg class="shape-1 d-none d-sm-block" viewBox="0 0 240.83 240.83" xmlns="http://www.w3.org/2000/svg">
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(120.42 -49.88) rotate(45)"></rect>
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(-49.88 120.42) rotate(-45)"></rect></svg
                    ><svg class="shape-2 d-none d-sm-block" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"></circle></svg>
                    <div class="device-wrapper">
                        <div class="device" data-device="iPhoneX" data-orientation="portrait" data-color="black">
                            <div class="screen bg-black">
                                <!-- PUT CONTENTS HERE:-->
                                <!-- * * This can be a video, image, or just about anything else.-->
                                <!-- * * Set the max width of your media to 100% and the height to-->
                                <!-- * * 100% like the demo example below.-->
                                <video muted="muted" autoplay="" loop="" style="max-width: 100%; height: 100%"><source src="assets/img/VIDEO-2021-07-14-21-27-01.mp4" type="video/mp4" /></video>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>



<!-- Quote/testimonial aside-->
<aside class="text-center bg-gradient-primary-to-secondary">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-xl-8">
                <div class="h2 fs-1 text-white mb-4">"A good device can serve its user for years and a bad device will punish its user for years!"</div>
                <img src="{% static 'assets/img/hhh.png' %}" alt="..." style="height: 15rem" />
            </div>
        </div>
    </div>
</aside>
<!-- App features section-->
<section id="features">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-8 order-lg-1 mb-5 mb-lg-0">
                <div class="container-fluid px-5">
                    <div class="row gx-5">
                        <div class="col-md-6 mb-5">
                            <!-- Feature item-->
                            <div class="text-center">
                                <i class="bi-phone icon-feature text-gradient d-block mb-3"></i>
                                <h3 class="font-alt">SELL DEVICES!</h3>
                                <p class="text-muted mb-0">You can sell your devices and prices will be discussed through professional means</p>
                                <div class="btn btn-light mt-3">
                                    <a class="bi bi-chevron-right" href="{% url 'main:home'%}#SELLDEVICES" >Sell Devices Now</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 mb-5">
                            <!-- Feature item-->
                            <div class="text-center">
                                <i class="bi-laptop icon-feature text-gradient d-block mb-3"></i>
                                <h3 class="font-alt">BUY DEVICES</h3>
                                <p class="text-muted mb-0">We sell a large variety of brands . Ranging from iphones to itels for a reasonable price</p>
                                <div class="btn btn-light mt-3">
                                    <a class="bi bi-chevron-right" href="{% url 'main:home'%}#BUYDEVICES">Buy Devices Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-5 mb-md-0">
                            <!-- Feature item-->
                            <div class="text-center">
                                <i class="bi-gift icon-feature text-gradient d-block mb-3"></i>
                                <h3 class="font-alt">BIDDING</h3>
                                <p class="text-muted mb-0">Every Friday is bidding friday, devices will be put up for aunctioning!</p>
                                <div class="btn btn-light mt-3">
                                    <a class="bi bi-chevron-right" href="{% url 'main:home'%}#PLACEABID">Start Bidding Now</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <!-- Feature item-->
                            <div class="text-center">
                                <i class="bi-patch-check icon-feature text-gradient d-block mb-3"></i>
                                <h3 class="font-alt">FIXING DEVICES</h3>
                                <p class="text-muted mb-0">We can fix your devices in real time </p>
                                <div class="btn btn-light mt-3">
                                    <a class="bi bi-chevron-right" href="{% url 'main:home'%}#FIXUP">Fix Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 order-lg-0">
                <!-- Features section device mockup-->
                <div class="features-device-mockup">
                    <svg class="circle" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                        <defs>
                            <linearGradient id="circleGradient" gradientTransform="rotate(45)">
                                <stop class="gradient-start-color" offset="0%"></stop>
                                <stop class="gradient-end-color" offset="100%"></stop>
                            </linearGradient>
                        </defs>
                        <circle cx="50" cy="50" r="50"></circle></svg
                    ><svg class="shape-1 d-none d-sm-block" viewBox="0 0 240.83 240.83" xmlns="http://www.w3.org/2000/svg">
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(120.42 -49.88) rotate(45)"></rect>
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(-49.88 120.42) rotate(-45)"></rect></svg
                    ><svg class="shape-2 d-none d-sm-block" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"></circle></svg>
                    <div class="device-wrapper">
                        <div class="device" data-device="iPhoneX" data-orientation="portrait" data-color="black">
                            <div class="screen bg-black">
                                <!-- PUT CONTENTS HERE:-->
                                <!-- * * This can be a video, image, or just about anything else.-->
                                <!-- * * Set the max width of your media to 100% and the height to-->
                                <!-- * * 100% like the demo example below.-->
                                <video muted="muted" autoplay="" loop="" style="max-width: 100%; height: 100%"><source src="https://tyre-project.s3.us-east-2.amazonaws.com/goalifix/assets/img/demo-screen.mp4" type="video/mp4" /></video>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Basic features section-->
<!-- <section  id="ABOUTUS" class="bg-light">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center justify-content-lg-between">
            <div class="col-12 col-lg-5">
                <h2 class="display-4 lh-1 mb-4">ABOUT US</h2>
                <p class="lead fw-normal text-muted mb-5 mb-lg-0">Goalifix is a company found by Anagbogu Akaolisa Godwin .This company has been running for 8 good years with over 1000 satisfied customers .Goalifix is a company that sells various devices ranging from phones to laptops to gadgets and much more electronic devices.</p>
            </div>
            <div class="col-sm-8 col-md-6">
                <div class="px-5 px-sm-0"><img class="img-fluid rounded-circle" src="{% static 'assets/img/pppp.jpg' %}" alt="..." /></div>
            </div>
        </div>
    </div>
</section> -->
<!--contact us-->
<div id="FINDUSNOW" class="section p-5">
    <div style="margin-top:50px">
    <div class="container">
        <div class="row g-4">
            <div class="col-md">
                
                <div class="h2 text-center mb-4"> CONTACT US</div>
                <ul class="list-group list-group-flush lead">
                    <li class="list-group-item">
                        <span class="fw-bold">ADRESS:</span> Suite 26 His grace plaza ,4 Francis oremeji street,computer village ,Ikeja
                    </li>
                    <li class="list-group-item">
                        <span class="fw-bold">PHONE:</span>  (+234)8163983818
                    </li>
                    <li class="list-group-item">
                        <span class="fw-bold">Email:</span>  goalflixltd@gmail.com
                    </li>
                    <li class="list-group-item">
                        <span class="fw-bold">DATE:</span>  Click on apply now 
                    </li>
                </ul>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock%}